server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Handle frontend routing (React / Angular / SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static file caching (optional but good)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1d;
        add_header Cache-Control "public";
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
